doc/source/reference/bruker.rst
nmrglue/fileio/bruker.py

The nmrglue.bruker.scale_pdata function scales processed Bruker data in the
same manner as is done in Topspin and other programs.  The scale_data
parameter added to nmrglue.bruker.read_pdata will perform this scaling during
reading of the processed data.

ENH: nmrglue.bruker.scale_pdata function

---

nmrglue/process/__init__.py
nmrglue/process/proc_autophase.py

An initial implementation of automatic phase correction for consideration.
This adds a new function to `proc_base` of `autops`, alongside two example
phase optimisation (scoring) algorithms: ACME and a naive peak minima approach.
Standard algorithms can be selected by name ('acme', 'peak_minima') while
custom algorithms can be provided as a function.
A [demo notebook is available](https://github.com/mfitzp/ipython-notebooks/blob/master/public/Automatic%20phase%20correction%20of%20NMR%20spectra.ipynb).

Automatic phase correction

---

nmrglue/process/proc_autophase.py

Will also work with 3D and 4D datasets. 
Returning the p0 and p1 values does not seem to work for me (p0, p1) remanins = (0, 0) after closing the matplotlib window. But this seems to be related to matplotlib version and/or mode of use (ipython, spyder or terminal), so I will let it be for now and fall back to the printed values of p0 and p1

Modified data selection so that direct dimension is picked up. 

---

nmrglue/fileio/pipe.py

Reading of NMRPipe files where the order of the axes ends with dimensions 1 or
2 is now possible.  Previously this would cause an error.

BUG: Reading NMRPipe 3D/4D with last axes 1 or 2

---

doc/source/reference/bruker.rst
examples/bruker_processed_1d/bruker_processed_1d.py
nmrglue/fileio/bruker.py

Hello nmrglue community: 
In this bruker-ppm_scale branch the fileio.bruker module will use information from Bruker 'procs' files when available.  If the 'procs' information is available the spectrum read by `bruker.read_pdata`, `bruker.read` or `bruker.read_lowmem` can be referenced correctly by using the updated `bruker.guess_udic` and  `fileiobase.uc_from_udic`. Please see 'examples/bruker_processed_1d/bruker_processed_1d.py' for an example. I will keep the example dataset accessible  (which is referenced properly) [here](https://www.dropbox.com/sh/mcg5fpwt20cjbdu/AAARo0jzQtH5SofJY-Xgj6Rva?dl=0) until these issues are resolved. This pull-request in part addresses issue #13  and I think it is a first poke at issue  #21.
Also, the example given should re-open issue #28. To match the …

Fix: Bruker ppm scale and intensity scale.

---

examples/bruker_processed_2d/bruker_processed_2d.py
nmrglue/fileio/bruker.py

For consideration: a fix for issue #49; when Bruker parameters STSI and/or STSR are set, the spectrum read by `bruker.read_pdata` is incorrectly referenced. 
An optional bool parameter was added to `bruker.guess_udic` called `strip_fake`. If set to `True` and if the dic has the parameters STSI or STSR  the sweep width and carrier frequency is faked so that `unit_conversion` objects can be used like normal.

ENH: reference processed Bruker strip transformed data

---

nmrglue/fileio/bruker.py

When reading Bruker sub-matrices with the read_pdata_binary or read_pdata
function in the bruker module the sub-matrices are only re-ordered once.
Previously two re-ordering were performed which resulted in incorrect data
being returned by these functions.
closes #58

BUG: Bruker sub-matices only reordered once

---

nmrglue/fileio/bruker.py

Currently, `bruker.guess_udic` and `bruker.add_axis_to_udic` fail when acqus files are unavailable or if they are called with `read_acqus=False`. Most of the parameters which it tries to look up in acqus are also available in procs. I have added conditionals to `bruker.add_axis_to_udic` where spectral width, carrier offset, axis name and acquisition mode will be looked up in procs as well as acqus. Most of the places, preference is given to the acqus files, but there are some use cases (such as post-acquisition re-scaling of spectral widths) where one should be reading specifically from the procs files.
This PR does not change the default behaviour of the functions.

Bruker guess_udic  now works when read_acqus=False

---

nmrglue/analysis/leastsqbound.py
nmrglue/analysis/linesh.py
nmrglue/analysis/tests/test_analysis_linesh.py

The ``_check_func`` issue is due to ``int < (int,)`` working in 2.7 (the first return value from ``_check_func`` is a shape tuple), but raising an exception in 3.x
The ``list(zip)`` fix is a standard 2.7 -> 3.x conversion issue.

Fix a couple of Python 3.x issues for fit_spectrum

---

nmrglue/fileio/simpson.py

Simpson can generate multiple datasets when multiple detect operators are specified. These are written as concatenated datasets and the number of such datasets is indicated by the keyword 'NELEM' in the simpson text and binary data formats. This PR fixes the functions read_text and read_binary to read in such a dataset. In cases where there is only a single FID, the keyword 'NELEM' is set to 1 and the data will be read in as usual, but an extra key 'NELEM' will be added to the dictionary. With this functionality, it is not possible to write data in xreim, xyreim and raw_binary formats, so those functions are not modified.
An example file in the text format is attached.
[out.fid.zip](https://github.com/jjhelmus/nmrglue/files/2223267/out.fid.zip)

Reading simpson files: fixes cases where multiple FIDs are concatenated

---

nmrglue/fileio/bruker.py

Currently, the functionality to write files in Bruker's formats is pretty good, but the files are not written out in a way that will make them accessible from Topspin. 2 things need to be done to make this happen: (i) Write acquN files in addition to acquNs files and (ii) write out the procN and procNs files in the correct subfolders. These commits give options to the user to do these things via `write` and `read` functions in `bruker.py`. The following changes are made:
1. `bruker.write` will now write acquN files in addition to acquNs files to the given directory. These will be identical files. Another option was to read and write out the `acquN`, but that adds unnecessary keys to the dictionary. This is a change in default behaviour, but it seems harmless to me even if the purpose of …

Read and write files so that Topspin can read them

---

nmrglue/fileio/pipe.py

3D nmrpipe file that was applied 'nmrPipe -fn EXT...' in z-dim could not be loaded by nmrglue.pipe.read().
I think, the trouble was originated length of z-dim was given by FDF\*FTSIZE or FDF\*TDSIZE. nmrPipe doesn't touch those parameters even EXT was applied. I would suggest using FDF\*X1 and FDF\*XN parameters for EXT applied data.

Modification of pipe.py for handling data that was applied  'nmrPipe -fn EXT' in z-dim

---

nmrglue/process/proc_autophase.py

axisbg is deprecated since matplotlib 2.0.0
https://matplotlib.org/api/prev_api_changes/api_changes_2.0.0.html?highlight=axisbg

replace matplotlib deprecated axisbg with facecolor

---

nmrglue/fileio/bruker.py

The `bruker.guess_udic` and the underlying `add_axes_to_udic` only looked up parameters present in the `acqus` file and failed for higher dimensions. The `SW_h` key is not available for indirect dimensions and the spectral width is now calculated from `SW` and `SFO1` parameters. This PR does not change default behavior.

Correctly guessing spectral widths in multidimensional datasets

---

nmrglue/analysis/peakpick.py

Fix the following FutureWarning caused by a recent numpy version (at
least 1.16.4, maybe even before that):
nmrglue/analysis/peakpick.py:398: FutureWarning: Using a non-tuple
sequence for multidimensional indexing is deprecated; use
`arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be
interpreted as an array index, `arr[np.array(seq)]`, which will result
either in an error or a different result.
return np.atleast_1d(np.squeeze(data[s])

Fix FutureWarning in peak picking

---

nmrglue/fileio/bruker.py

Allow text values in JCAMP files which aren't surrounded by angle
brackets. Remove angle brackets only if they indeed surround the value.
Try parsing the value to numerical types, and return a string if parsing
fails.
Although I didn't read the JCAMP specification, a quick look at [JCAMP for NMR (1993), Example 4](http://jcamp-dx.org/protocols/dxnmr01.pdf) makes me believe that the angle brackets are not required for text values.

Allow text values in JCAMP files without brackets

---

nmrglue/util/xcpy.cfg
nmrglue/util/xcpy.py
nmrglue/util/xcpy_test.py

Bruker-Topspin now being freely [available](https://www.bruker.com/service/support-upgrades/software-downloads/nmr/free-topspin-processing/nmr-topspin-license-for-academia.html) under an academic licence, this is a feature request that comes up often for me, and has [popped](https://groups.google.com/forum/#!topic/nmrglue-discuss/FPxhw4M6OLs) up on the `nmrglue-discuss` group as well. The file `xcpy.py`, which is included in the `nmrglue/util` folder, will allow the use of nmrglue (and any other cpython script) from within Topspin. It is a lightly polished version of what has been sitting in one of my repositories for sometime now, and takes some suggestions from the nmrglue-discuss thread. This should go nicely with the ability of nmrglue to read and write (#85, #88) bruker datasets, and …

xcpy: Interfacing with external scripts from Topspin

---

nmrglue/fileio/bruker.py

Allow to provide a list of possible encodings for reading JCAMP files,
and use the first encoding which doesn't raise an UnicodeDecodeError.
Suppress such errors, except when all provided encodings fail.
Keep the current behaviour by choosing the default encoding if no
encoding is specified.
I'm not sure if you want to pull this, but for my purposes this is easier and more futureproof than converting the JCAMP files on operating system level.

Allow different encodings for reading JCAMP files

---

nmrglue/util/xcpy.py

This PR now allows the user to write out multiple locations to search for scripts. 
And better comments and docstrings for the existing functions as well

xcpy: search multiple directories for a script

---

nmrglue/process/proc_autophase.py
nmrglue/process/proc_lp.py

Use correct parameter names in docstrings and remove unused variables.

Docstring fixes and cleanup

---

nmrglue/process/proc_autophase.py

This PR does 3 things to the `autops` function:
1. Allows an optional `return_phases` argument. If set to `True`, the optimized phases will be returned. By default, this is set to `False`.
2. Allows additional (optional) keyword arguments to be passed to the `scipy.optimize.fmin`. The default options work fine most of the time for `autops`, but this way, one has the option to turn off the (sometimes irritating) convergence messages (using `disp=False`). Also `maxiter` and `ftol` might  be useful in some cases. The complete list of options is documented [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin.html).
3.  "Normalizes"  the return value of the "acme" function to a reasonable number. The current return value is very high and sometimes causes convergence …

Additional options for autops

---

nmrglue/fileio/jcampdx.py
tests/test_jcampdx.py

Quite often there's all kinds of metadata embedded in JCAMP-DX files. This PR changes the parser behavior to consider only the relevant DATATYPE sections, namely NMR SPECTRUM and NMR FID. Error messaging is also improved for cases where no data is found after all.
In addition, this PR fixes a bug in recognition of JCAMP pseudodigit format.

Only consider relevant DATATYPEs (NMR SPECTRUM / FID) when reading JCAMP-DX

---

doc/source/tutorial.rst

Tutorial introduction rst file modified to include instructions to download nmrglue to colabs.
A first step to being used on that platform.

Colabs and nmrglue

---

doc/source/install.rst
doc/source/reference/bruker.rst
doc/source/reference/index.rst
doc/source/reference/sparky.rst
doc/source/reference/xcpy.rst
doc/source/tutorial.rst

This PR updates the documentation at these places:
1. New functions in `fileio.simpson.py` and `fileio.bruker.py` catalogued
2. A new file for documenting `misc.xcpy.py`
3. Updated installation instructions and requirements (`install.rst`) 
4. Updated `tutorial.rst` (correct links, more information on filetypes that nmrglue can handle)
5. Updated instructions to use matplotllib in `tutorial.rst`

Updates to the documentation

---

.gitignore
nmrglue/fileio/bruker.py
nmrglue/fileio/tests/test_bruker.py

Passing proc and procs files location using parameter `procs_files` in read_fid or read_pdata generate an error. 
` dic, data = ng.bruker.read_pdata(specdir, procs_files = ["somepath/procs"]) `
generate an error: 
```
for f in ["procs", "proc2s", "proc3s", "proc4s"]:
>               if os.path.isfile(os.path.join(pdata_path, f)):
E               UnboundLocalError: local variable 'pdata_path' referenced before assignment
../bruker.py:611: UnboundLocalError
```
This pull request proposes to solve this problem by a modification of `read_procs_file` function in `bruker.py`.  It  adds also some changes in the `read_acqus_file` so that both functions can accept absolute path for acqu(s) and proc(s) files.

Fix bug when passing specific procs_file in read_fid or read_pdata (Bruker imports)

---

nmrglue/fileio/bruker.py

Fixed a regression bug introduced by #134. It prevented `procNs` files from being read in from standard directories when `read_procs=True` and `procs_files=None` is given to the `bruker.read` function.

Regression Bugfix

---

nmrglue/fileio/__init__.py
nmrglue/fileio/spinsolve.py

I created the read and guess_udic for spinsolve data, as mentioned in issue #146.
The read function will work on a directory and a filename can be specified, otherwise the standard names are tried.
When I compared to other fileio scripts I realized that I put everything into one function instead of using smaller functions. I can still do this for a next iteration.
I also use the fileio/jcampdx.py script here to read the (optional) .dx file, I'm not sure if that is preferred or if it's better to copy (only) the necessary code here.
guess_udic uses acqu.par file parameters (should be always present), otherwise the .dx file header parameters are used (only when having a .dx file)

Created spinsolve.py

---

doc/source/reference/index.rst
doc/source/reference/spinsolve.rst
doc/source/tutorial.rst
nmrglue/fileio/jcampdx.py
nmrglue/fileio/spinsolve.py
tests/test_spinsolve.py

Few improvements to the spinsolve import module
* minor change to acqu.par parsing, e.g. now `["Sample"] == "EtOH"` before it was  `["Sample"] == "\"EtOH\""` (with additional quote marks)
* Added info to docs
* Tests added (the spectrum referenced in the test has not been added as the `/data/` folder is in .gitignore, where can I put it? Also, how to run the tests for the other modules (e.g. bruker)?

Add test and docs for fileio.spinsolve

---

nmrglue/fileio/spinsolve.py

If the an attribute contains an equal sign,  then `line.split("=")` returns more than 2 values and causes a
"ValueError: too many values to unpack (expected 2)"
Sorry for this,  I should have tested #151  more
This is particularly annoying since the SpinSolve userData stores custom data on a format that includes equals, so this bug will happen every time the user specify custom userData via the acquisition software.
`userData                            = "some_key=Some value;some_other_key=Other value"`

:bug: Fix bug in parse_spinsolve_par_line()

---

doc/source/devel/index.rst
nmrglue/fileio/pipe.py
tests/test_pipe.py

Hi Jonathan,
Thanks for making nmrglue! It's such a wonderful contribution to the NMR community. I have been using it for my work ever since you published your JBNMR paper and it has really empowered my NMR data analyses.
I have a use case whereby I need (want) to read NMRPipe data stored in memory rather than directly from disk. I've added this capability to the `nmrglue.pipe.read` function which can now accept `io.BytesIO` and `bytes` objects containing NMRPipe data. I have written tests which are passing. I think this change should remain entirely compatible with previous versions. Would you be willing to incorporate it? I'm also open to suggestions.

Read from binary stream

---

nmrglue/fileio/spinsolve.py

In older spinsolve software some parameters in acqu.par were stored just as string instead of a string between parentheses.
i.e.:
linearPrediction                    = no
instead of:
linearPrediction                    = "no"
Therefore "parse_spinsolve_par_line(line)" should return a string when int() and float() fails.

Fixed edge case in parse_spinsolve_par_line

---

nmrglue/fileio/pipe.py
tests/test_bruker.py
tests/test_pipe.py

Hi @kaustubhmote, I made a very minor change to the `nmrglue.pipe.read` function so that it deals with `pathlib.Path` objects by converting them back to strings. Not sure whether this is the ideal solution but I wrote a test for it which is passing. Hope that helps and happy to hear alternative ideas.

read nmrPipe data from pathlib.Path object

---

nmrglue/fileio/sparky.py

This PR fixes:
1. A bug in reading sparky .save files where no 'label' was applied to a 'peak'
2. Tries harder to read in the spectrum file, with some useful error message if it fails
3. Cleans up the function to use better names for internal variables (found it hard to follow the logic)

Bugfix in reading sparky .save files

---

nmrglue/analysis/leastsqbound.py

This fixes a break in nmrglue due to a reorganization of the `scipy.optimize` submodules in v1.8. The change is backward compatible with previous versions of `scipy`.

Bugfix for: Cannot import nmrglue with scipy v1.8

---

nmrglue/analysis/linesh.py
nmrglue/fileio/fileiobase.py
nmrglue/fileio/pipe.py
nmrglue/fileio/varian.py
nmrglue/process/pipe_proc.py
nmrglue/process/proc_base.py
nmrglue/util/misc.py

I have left out `seperate`, addressed in #139.

Fix typos found by codespell

---

nmrglue/util/xcpy.py
nmrglue/util/xcpy_test.py

The xcpy module is used within TopSpin, which includes Jython, which implements Python 2.
Remove changes applied to `nmrglue/util/xcpy.py` and `nmrglue/util/xcpy_test.py` in #178 and #179.
See https://github.com/jjhelmus/nmrglue/pull/179#issuecomment-1340210384.

Partially revert 1802772 and bbeb8aa

---

nmrglue/analysis/peakpick.py

Changed 'np.float' to 'float' in peakpick.py line 329 to fix the np.analysis.peakpick.pick() function. NumPy deprecated the np.float function in numpy 1.20.0 which broke the ng.analysis.peakpick.pick() function giving an error (see nmrglue issue #192). Changing 'np.float' to 'float' is the recommended fix by NumPy as it "will not modify any behavior and is safe." Using the float() function instead of np.float() looks to be consistent with the rest of the code in peakpick.py.

Changed 'np.float' to 'float' in peakpick.py line 329

---

nmrglue/analysis/peakpick.py
nmrglue/fileio/convert.py

This PR fixes the following:
1. `np.float` is now deprecated, which breaks peak-picking (#192). This is replaced by a call to `float`.
2. Use of lists as multiple slices is not allowed anymore. This broke several data conversion routines (#195). Lists are unpacked before being fed to the array as slices.
These changes are compatible with previous versions of numpy and nmrglue.

Fixes for deprecations in newer versions of numpy

---

examples/fitting_data/t1_measurements/pt.py
examples/plotting/plot_2d/plot_boxes.py
examples/plotting/plot_sparky_savefile/plot_sparky.py
nmrglue/analysis/linesh.py
nmrglue/analysis/peakpick.py
nmrglue/fileio/bruker.py
nmrglue/fileio/convert.py
nmrglue/fileio/glue.py
nmrglue/fileio/jcampdx.py
nmrglue/fileio/rnmrtk.py
nmrglue/fileio/table.py
nmrglue/fileio/varian.py
nmrglue/util/xcpy.py

It's faster.
Also a couple small changes here and there.

Use f-strings where possible

---

nmrglue/fileio/bruker.py

np.product was deprecated with NumPy 1.25 and will be removed in a future release.

remove use of np.product in favor of np.prod

---

nmrglue/fileio/bruker.py
tests/test_bruker_with_test_data.py

I somehow missed that the final version of PR #212 had a bug in directory variable name. I am fixing this, as well as adding a test to check this function. Plus some cleanup of the error message.

BugFix: directory variable in read_vdlist

---

nmrglue/analysis/peakpick.py
tests/test_peakpick.py

This PR addresses and fixes #215 by making the API for all algorithms work in the same way.  A self-contained test is also included for the `peakpick` module.

Peakpick testing

---

nmrglue/fileio/convert.py
tests/test_convert.py

The current conversion from bruker to csdm format always returns a csdm object with the time domain dimensions. In cases, when the data is read from `pdata` the dimension should be set to frequency domain.
Use the udic `freq` or `time` boolean query to check if the data dimension is freq or time domain and then generate the corresponding csdm dimensions.

bugfix: to_csdm converter should return freq and time dimension based on the data udic

---

nmrglue/fileio/__init__.py
nmrglue/fileio/rs2d.py
tests/test_rs2d.py

This PR adds the import module for the RS2D (https://rs2d.com/) / QUAD (https://quadsystems.tech/) format including universal dictionary functionality (guess_udic()).
Tests covering basic 1D and 2D experiments are included, and CC licensed test data is kindly provided by QUAD Systems. The test data set is free to be added to the nmrglue test data package. It is temporarily available at 
https://drive.google.com/file/d/1FXTuLV4FDK72KEC31zLFmkHDeNPEuDTo/view
, please let me know once you have downloaded it.
Special acknowledgements for Thomas Paris and Gaëtan Assemat from QUAD Systems for helping me to put this together!

Import for RS2D format

---

nmrglue/fileio/jeol.py

Fixes a bug in generating a formatted error message using an f-string. Discovered in #235 as `colab` seems to throw an error at import time, but a local installation does not. Fixes #235

fixed f-string bug: disallowed backslash character

---

nmrglue/process/proc_base.py

Fixes a bug in the left shift function `nmrglue.process.proc_base.ls()`.
Problem:
When `proc_base.ls()` is called with the default argument `pts=0`, it overwrites the entire `data` array with zeros, instead of leaving the data unchanged. The issue arises because the line "`data[..., -int(pts):] = 0`" zeroes out the entire data when `pts` is 0.
Fix:
- Added a simple guard clause to `ls`:
```
if int(pts) == 0:
return data
```
- Changed the default parameter from `pts=0.0` to `pts=0` in a few functions for clarity, especially since their docstrings describe `pts` as int.
Note: My previous pull request incorrectly claimed this bug existed for both the left shift `ls()` and right shift `rs()` functions. I have closed and replaced that old pull request with this one, because this bug only …

bugfix: Fix zero-shift bug in `proc_base.ls`

---

nmrglue/process/proc_base.py
nmrglue/process/proc_bl.py

`scipy.signal.gaussian` was deprecated in SciPy 1.1 after being moved to `scipy.signal.windows.gaussian`.

Fix deprecated scipy calls
